describe("Test Suite - Pruebas Orange HRM", () => {
    beforeEach(() => {
    // runs before each test in the block  <---- Super Important
    //We dont need to add any command, variable or catching the element in any test. Just running it at the top of all the test cases will be enough
        cy.visit("https://opensource-demo.orangehrmlive.com/")
    })   
    it("Validar pagina de inicio", () => {
        cy.get('.orangehrm-login-branding > img').should("be.visible")
        cy.get('.orangehrm-login-branding').should("be.visible")
        cy.get('.orangehrm-login-logo').should("be.visible")
        cy.get('.orangehrm-copyright-wrapper > :nth-child(1)').should("be.visible")
        cy.get('.orangehrm-copyright-wrapper > :nth-child(2)').should("be.visible")
        cy.get('.orangehrm-login-slot').should("be.visible")
        cy.get('.orangehrm-login-footer-sm').should("be.visible")
    })
    it("Log In de usuario y verificacion", () => {
        cy.get('[name="username"]').type("Admin")
        cy.get('[name="password"]').type("admin123")
        cy.get('.oxd-button').click()
        cy.get('.oxd-brand-banner > img').should("be.visible") // Verificamos que el logo siempre este en la parte superior de la pagina
        cy.get('.oxd-userdropdown-name').should("be.visible") // Verificamos que el nombre de usuario este siempre en la parte superior al iniciar sesion
        cy.get(':nth-child(1) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(2) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(3) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(4) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(5) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(6) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(7) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(8) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(9) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(10) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('[name="password"]').type("admin123")
        cy.get('.oxd-button--secondary').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(11) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
        cy.get(':nth-child(12) > .oxd-main-menu-item > .oxd-text').click()
        cy.get('.oxd-userdropdown-name').should("be.visible")
    })
})